export const gallery = [
  {
    nama: "Bunga Aster",
    url: "https://drive.google.com/uc?export=view&id=1WHRp7_pCl3kTJPTAw8r530FPmRmLS0mF",
    kategori: "Nature",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Bunga Merah",
    url: "https://drive.google.com/uc?export=view&id=1M2oIza_iHlFeIO56GNZYiDQIKXdFXQBg",
    kategori: "Nature",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Evaa",
    url: "https://drive.google.com/uc?export=view&id=1WHRp7_pCl3kTJPTAw8r530FPmRmLS0mF",
    kategori: "Tim 5",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Evaa",
    url: "https://drive.google.com/uc?export=view&id=1WHRp7_pCl3kTJPTAw8r530FPmRmLS0mF",
    kategori: "Tim 5",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Airplane View",
    url: "https://i.pinimg.com/564x/16/e7/b7/16e7b7c5efa3f4360205723f18004921.jpg",
    kategori: "Travel",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Airplane View",
    url: "https://drive.google.com/uc?export=view&id=1NUPqeUhMdiqNbkHenLXCdJezVXSFvib8",
    kategori: "Travel",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Brown Outfit",
    url: "https://i.pinimg.com/564x/24/3e/7e/243e7ec90fa90b9c4b76c217cd086186.jpg",
    kategori: "Fashion",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Brown Outfit",
    url: "https://i.pinimg.com/564x/24/3e/7e/243e7ec90fa90b9c4b76c217cd086186.jpg",
    kategori: "Fashion",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Gajelas",
    url: "https://i.pinimg.com/564x/ed/3c/d8/ed3cd8ca8089507f2eda31882c41808d.jpg",
    kategori: "Abstrak",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Gajelas",
    url: "https://i.pinimg.com/564x/ed/3c/d8/ed3cd8ca8089507f2eda31882c41808d.jpg",
    kategori: "Abstrak",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Mobil",
    url: "https://i.pinimg.com/564x/01/35/fe/0135fe701798974fdf6b2e24bc53b36b.jpg",
    kategori: "Sport",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Mobil",
    url: "https://i.pinimg.com/564x/01/35/fe/0135fe701798974fdf6b2e24bc53b36b.jpg",
    kategori: "Sport",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "aesthetic art",
    url: "https://i.pinimg.com/564x/ec/27/1e/ec271ee185c6e56eac195853504e2861.jpg",
    kategori: "Art",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "aesthetic art",
    url: "https://i.pinimg.com/564x/ec/27/1e/ec271ee185c6e56eac195853504e2861.jpg",
    kategori: "Art",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Spaghetti",
    url: "https://drive.google.com/uc?export=view&id=1J1glleiWgBuKbv_8dM58IAH05rdh4Nwu",
    kategori: "Food & Drink",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Lunch",
    url: "https://drive.google.com/uc?export=view&id=1t70uNRkNUPx9PC0FTuReQ3YLTTrmzfnD",
    kategori: "Food & Drink",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "kota A",
    url: "https://drive.google.com/uc?export=view&id=1UUbFFkSJTBXZMpoCpnBzHE3-4EEOsCOo",
    kategori: "Cities",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Night View",
    url: "https://drive.google.com/uc?export=view&id=1NwkH-RtVYdCHweFeBobKxafk-qppJvxk",
    kategori: "Cities",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Kucing Oren ",
    url: "https://i.pinimg.com/564x/d1/d8/3e/d1d83e26ecda8b3eda4a479e28dbf6f4.jpg",
    kategori: "Animals",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
  {
    nama: "Kucing Oren ",
    url: "https://drive.google.com/uc?export=view&id=1m6CT-7AzN52hCYdttVpsq9kw-LNxQu7W",
    kategori: "Animals",
    desc: "Bunga aster dapat diartikan sebagai rasa kebijaksanaan,keberanian, dan keyakinan",
  },
];
